# Generated by Django 5.2.6 on 2025-11-26 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoryApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='photo',
        ),
        migrations.AddField(
            model_name='memory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memory',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memory',
            name='mood',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='revision',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='memory',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='memory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MemoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='memoryApp.memory')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
