# Generated by Django 5.2.6 on 2025-11-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoryApp', '0002_remove_memory_photo_memory_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoryimage',
            name='image',
            field=models.ImageField(upload_to='memory_photos/'),
        ),
    ]
