# Generated by Django 5.2.8 on 2026-02-16 09:16

import memoryApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoryApp', '0003_alter_memoryimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/', validators=[memoryApp.validators.validate_audio_size, memoryApp.validators.validate_audio_extension]),
        ),
        migrations.AlterField(
            model_name='memory',
            name='mood',
            field=models.IntegerField(blank=True, choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Neutral'), (4, 'Good'), (5, 'Very Good')], null=True),
        ),
        migrations.AlterField(
            model_name='memoryimage',
            name='image',
            field=models.ImageField(upload_to='memory_photos/', validators=[memoryApp.validators.validate_image_size, memoryApp.validators.validate_image_extension]),
        ),
    ]
