# Generated by Django 5.2.8 on 2026-02-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoryApp', '0004_alter_memory_audio_alter_memory_mood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='location_name',
            field=models.CharField(blank=True, default='Unknown location', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='memory_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='mood',
            field=models.IntegerField(blank=True, choices=[(1, 'CALM'), (2, 'HAPPY'), (3, 'SAD'), (4, 'ANXIOUS'), (5, 'EXCITED'), (6, 'REFLECTIVE'), (7, 'GRATEFUL'), (8, 'ANGRY'), (9, 'LONELY'), (10, 'CONTENT')], null=True),
        ),
    ]
