# Generated by Django 5.2.8 on 2026-02-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoryApp', '0005_memory_location_name_memory_memory_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='location_name',
            field=models.CharField(blank=True, default='Unknown location', null=True),
        ),
    ]
