# Generated by Django 5.2.11 on 2026-03-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoryApp', '0006_alter_memory_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='location_name',
            field=models.CharField(blank=True, default='Unknown location', max_length=555, null=True),
        ),
    ]
