# Generated by Django 5.2.11 on 2026-03-06 19:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoryApp', '0007_alter_memory_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoryimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
