# Generated by Django 5.1.1 on 2026-03-26 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoryApp', '0008_alter_memoryimage_image'),
    ]

    operations = [
    ]
