# Generated by Django 5.1.1 on 2026-03-29 17:56

import cloudinary.models
import memoryApp.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memoryApp', '0009_audio_cloudinary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='audio',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[memoryApp.validators.validate_audio_size, memoryApp.validators.validate_audio_extension, memoryApp.validators.validate_audio_duration], verbose_name='audio'),
        ),
    ]
